import = ["/home/andrew/.config/alacritty/themes/gruvbox-dark.toml"]

[cursor.style]
blinking = "On"
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 11.0

[font.normal]
family = "Geist Mono Nerd Font"
style = "Regular"

[window]
opacity = 0.8
dimensions = { columns = 75, lines = 25 }
resize_increments = true
