#import = ["/home/aconlin/.config/alacritty/themes/gruxbox-dark.toml"]

[cursor.style]
blinking = "On"
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 13.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
opacity = 0.8
dimensions = { columns = 75, lines = 25 }
