import = ["/home/andrew/.config/alacritty/themes/tokyonight.toml"]

[cursor.style]
blinking = "On"
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 9.0

[font.normal]
family = "Geist Mono"
style = "Regular"

[window]
opacity = 0.8
